services:
  web:
    build: ./brian_hornbrook_portfolio
    container_name: brian_hornbrook_portfolio
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - entrypoint.prd.sh
    labels:
      - "traefik.enable=true"
        # Routers
      # http
      - "traefik.http.routers.brian_hornbrook_portfolio.rule=Host(`yourhonestprogrammer.com`) || Host(`www.yourhonestprogrammer.com`)"
      - "traefik.http.routers.brian_hornbrook_portfolio.entrypoints=web"
      - "traefik.http.routers.brian_hornbrook_portfolio.middlewares=redirect"
      # https
      - "traefik.http.routers.brian_hornbrook_portfolio-secure.rule=Host(`yourhonestprogrammer.com`) || Host(`www.yourhonestprogrammer.com`)"
      - "traefik.http.routers.brian_hornbrook_portfolio-secure.entrypoints=websecure"
      - "traefik.http.routers.brian_hornbrook_portfolio-secure.tls.certresolver=myresolver"
      # Services
      - "traefik.http.services.brian_hornbrook_portfolio-secure.loadbalancer.server.port=8000"
      # Redirect Scheme HTTP -> HTTPS
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=true"
networks:
  web:
    external: true